name: Setup DB
inputs:
  kind:
    description: dev or test
    default: dev
runs:
  using: composite
  steps:
    - run: cp ./.env.sample ./.env.local
      shell: bash
    - run: pnpm dev:db:setup
      if: ${{ inputs.kind == 'dev' }}
      shell: bash
    - run: pnpm test:db:setup
      if: ${{ inputs.kind == 'test' }}
      shell: bash
