name: migration

on:
  push:
    branches:
      - main
    paths:
      - prisma/**
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    # please remove this after you set the secrsts
    if: false
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-db
      - run: pnpm db:deploy
        env:
          DATABASE_URL: ${{secrets.POSTGRES_URL}}
